#if !canImport(ObjectiveC)
import XCTest

extension CSwiftVTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CSwiftVTests = [
        ("testPerformance", testPerformance),
        ("testThatCanReturnKeyedRows", testThatCanReturnKeyedRows),
        ("testThatItCanGetCells", testThatItCanGetCells),
        ("testThatItCanGetCellsFromAstring", testThatItCanGetCellsFromAstring),
        ("testThatItCanParseArbitrarySeparators", testThatItCanParseArbitrarySeparators),
        ("testThatItParsesFieldswithCommasInQuotes", testThatItParsesFieldswithCommasInQuotes),
        ("testThatItParsesFieldswithNewLinesInQuotes", testThatItParsesFieldswithNewLinesInQuotes),
        ("testThatItParsesFieldswithQuotes", testThatItParsesFieldswithQuotes),
        ("testThatItParsesFieldswithQuotesInQuotes", testThatItParsesFieldswithQuotesInQuotes),
        ("testThatItParsesHeadersCorrectly", testThatItParsesHeadersCorrectly),
        ("testThatItParsesLinesSeperatedByNewLines", testThatItParsesLinesSeperatedByNewLines),
        ("testThatItParsesLinesSeperatedByNewLinesNoCR", testThatItParsesLinesSeperatedByNewLinesNoCR),
        ("testThatItParsesLinesSeperatedByNewLinesWithoutNewLineAtEnd", testThatItParsesLinesSeperatedByNewLinesWithoutNewLineAtEnd),
        ("testThatItParsesRowsLongerThanHeaders", testThatItParsesRowsLongerThanHeaders),
        ("testThatItParsesRowsWithoutHeaders", testThatItParsesRowsWithoutHeaders),
        ("testTheBadOne", testTheBadOne),
        ("testWhenCellsAreEmpty", testWhenCellsAreEmpty),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CSwiftVTests.__allTests__CSwiftVTests),
    ]
}
#endif
